[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib", "node_modules"]

solc = "0.8.20"
auto_detect_solc = false

optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
